### PR TITLE
Fix _index and HGNC symbol indexing

### PR DESCRIPTION
**Pull request by mossjacob**
### Summary :memo:

Fixes a one-line bugs in the index key extraction of an AnnData store as well as the biomart processor.

### Details

- Instead of accessing "_index" which does not exist as a key, access the _index attr which links to the key.

- Removes the line which limits genes to those with no HGNC symbol (is there a reason this is there?)
- Uses latest LaminDB's `MappedCollection` instead

### CODE REVIEW

**Comment by jkobject** [comment]
Hello @mossjacob,

thanks for the update! Just one question about the mapped.py update, any explanation? I take this file from lamindb's mapped function. Can you explain what it is changing?

Also, there was quite some updates recently on lamindb, if you want to update it from their version and make a PR, it would be super useful!  
https://github.com/laminlabs/lamindb/blame/2e3ebeac61608f1a83f50583890db23bfec595d7/lamindb/core/_mapped_collection.py#L55 

Best,

**Comment by mossjacob** [comment]
Hello @jkobject,

I think it was a bug in that line--the index of var couldn't be accessed as it was. I did not realise that this file was copied from lamin--how come you don't just import MappedCollection from lamindb? I believe lamindb is a dependency of this project?

Best,
Jacob

**Comment by jkobject** [comment]
Initially I had updates that were specific to scdataloader. Now they all got added to lamin. But I have some plans to update this part soon too so I was keeping it like this.

**Comment by mossjacob** [comment]
Hi,

I've updated the PR to use the latest Lamin mapped collection and added separately the `check_aligned_vars` function to the scDataLoader `Dataset`. How does it look to you?

**Pull request merged**
